classdef WaitDialog < handle
    
    properties (GetAccess='public', SetAccess='private')
        handler;
        main_string;
        sub_string;
    end;
    methods
        function obj = WaitDialog()
            sizeW = [300 170];
            screensize = get(0, 'ScreenSize');
            xpos = ceil((screensize(3)-sizeW(1))/2);
            ypos = ceil((screensize(4)-sizeW(2))/2);
            obj.handler = dialog('Name', '', ...
                'Position', [xpos ypos sizeW], ...
                'Visible', 'off', ...
                'WindowStyle', 'normal');

            txt_width = sizeW(1) - 40;
            uicontrol('Parent', obj.handler, ...
               'Style', 'text', ...
               'Position', [20 135 txt_width 25], ...
               'FontSize', 11, ...
               'String', 'Optimization in progress...');

            btn_width = 70;
            btn_left = (sizeW(1) - btn_width)/2;
            uicontrol('Parent', obj.handler, ...
               'Position', [btn_left 15 btn_width 25], ...
               'String', 'Abort', ...
               'FontSize', 9, ...
               'Callback', {@WaitDialog.abort, obj});
           setappdata(obj.handler, 'abort', 0);

           uicontrol('Parent', obj.handler, ...
                'Style', 'text', ...
                'BackgroundColor', 'black', ...
                'Visible', 'on', ...
                'Position', [20 50 txt_width 80]);
            uicontrol('Parent', obj.handler, ...
                'Style', 'text', ...
                'BackgroundColor', 'white', ...
                'Visible', 'on', ...
                'Position', [21 51 txt_width-2 78]);

            obj.main_string = uicontrol('Parent', obj.handler, ...
                'Style', 'text', ...
                'Position', [21 110 txt_width-2 19], ...
                'BackgroundColor', 'white', ...
                'HorizontalAlignment', 'left', ...
                'FontSize', 9, ...
                'String', 'Starting...');

            sub_width = txt_width-2-(35-21);
            obj.sub_string = uicontrol('Parent', obj.handler, ...
                'Style', 'text', ...
                'Position', [35 90 sub_width 20], ...
                'BackgroundColor', 'white', ...
                'HorizontalAlignment', 'left', ...
                'FontSize', 9, ...
                'String', '');
            
            set(obj.handler, 'Visible', 'on');
            drawnow;
        end;
        function delete(obj)
            delete(obj.handler);
        end;
        function terminate(obj)
            if ~getappdata(obj.handler, 'abort')
                return;
            end;
            delete(obj);
            throw(MException('MyERR:Terminated', 'Operation aborted by user'));
        end;
        function setMainString(obj, str)
            set(obj.main_string, 'String', str);
            set(obj.sub_string, 'String', '');
            drawnow;
        end;
        function setSubString(obj, str)
            set(obj.sub_string, 'String', str);
            drawnow;
        end;
    end;
    methods (Static, Access='public')
        function abort(~, ~, obj)
            setappdata(obj.handler, 'abort', 1);
        end;
    end;
end